<a href="https://colab.research.google.com/github/elmago07/AI-ML-Learnings/blob/main/pandas_learnings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
######Tow data structures in pandas:series and DataFrame######

In [ ]:
import pandas as pd
###creating a series from a list###
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
####Data FRame###

data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris']}
df = pd.DataFrame(data)
print(df)

      Team          Driver
0  Redbull  Max Verstappen
1   Ferrai        Hamilton
2  McLaren    Lando Norris

In [ ]:
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes

In [ ]:
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df.size)
print(df.ndim)
print(df.shape)

12
2
(3, 4)

In [9]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df.index)
print(df.columns)
print(df.values)
print(df.axes)
print(df.dtypes)

RangeIndex(start=0, stop=3, step=1)
Index(['Team', 'Driver', 'Tyre', 'Power_Unit'], dtype='object')
[['Redbull' 'Max Verstappen' 'hard' 'Honda']
 ['Ferrai' 'Hamilton' 'soft' 'Ferrari']
 ['McLaren' 'Lando Norris' 'soft' 'Mercedes']]
[RangeIndex(start=0, stop=3, step=1), Index(['Team', 'Driver', 'Tyre', 'Power_Unit'], dtype='object')]
Team          object
Driver        object
Tyre          object
Power_Unit    object
dtype: object

In [10]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df.info() #gives the entire data of data frame instead of calling one one method everyttime

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Team        3 non-null      object
 1   Driver      3 non-null      object
 2   Tyre        3 non-null      object
 3   Power_Unit  3 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes

In [12]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df.describe() #gives basic statics of data

           Team          Driver  Tyre Power_Unit
count         3               3     3          3
unique        3               3     2          3
top     Redbull  Max Verstappen  soft      Honda
freq          1               1     2          1

In [14]:
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
df.memory_usage() #gives memeory usage of each column

Index         132
Team           24
Driver         24
Tyre           24
Power_Unit     24
dtype: int64

In [18]:
# Accessing data in data frame
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
#df.Team
df.Driver

0    Max Verstappen
1          Hamilton
2      Lando Norris
Name: Driver, dtype: object

In [30]:
### Acessing rows using iloc and loc
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df)
df.iloc[0:2] #Access row by position using iloc

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari

In [26]:
### Acessing rows using iloc and loc
import pandas as pd
data = {'Team': ['Redbull', 'Ferrai', 'McLaren'],
        'Driver': ['Max Verstappen', 'Hamilton', 'Lando Norris'],
        'Tyre': ['hard', 'soft', 'soft'],
        'Power_Unit': ['Honda', 'Ferrari', 'Mercedes']}
df = pd.DataFrame(data)
print(df)
df.loc[0:2] ##access row by label using loc

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes

      Team          Driver  Tyre Power_Unit
0  Redbull  Max Verstappen  hard      Honda
1   Ferrai        Hamilton  soft    Ferrari
2  McLaren    Lando Norris  soft   Mercedes

In [2]:
###Importing & Exploring a DataSet
import pandas as pd
df = pd.read_csv('worldbank_indicators.csv')
df

,country_code,year,remittances_received_usd,remittances_paid_usd,remittances_pct_gdp,gdp_usd,gdp_per_capita_usd,gdp_growth_pct,gni_per_capita_usd,inflation_cpi_pct,...,mobile_money_accounts_pct,country_name,region,income_group,capital_city,latitude,longitude,source_engine,remittances_per_capita_usd,remittances_growth_yoy
0,1A,2010,3.778065e+10,5.423934e+10,2.332815,2.161398e+12,5944.952173,4.840642,5774.981239,NaN,...,9.604438,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,103.9162,NaN
1,1A,2011,3.894486e+10,6.766183e+10,1.900776,2.573068e+12,6915.827681,3.853204,6088.034560,NaN,...,9.382147,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,104.6750,3.08
2,1A,2012,4.593362e+10,7.449443e+10,2.048791,2.813568e+12,7384.106828,5.493754,6953.254327,NaN,...,9.157613,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,120.5511,17.95
3,1A,2013,4.722886e+10,8.559665e+10,2.026886,2.883690e+12,7376.028296,2.647321,7360.490201,NaN,...,8.472539,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,120.8040,2.82
4,1A,2014,5.312215e+10,8.700395e+10,2.226287,2.937036e+12,7338.350927,2.659752,7407.961860,NaN,...,7.240058,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,132.7287,12.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3705,ZW,2019,1.417012e+09,1.348057e+07,4.247931,3.335770e+10,2184.329239,-6.332450,2430.000000,255.304991,...,1.740080,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,92.7888,-0.75
3706,ZW,2020,1.832039e+09,2.170709e+07,5.728644,3.198033e+10,2059.674454,-7.816951,1980.000000,557.201817,...,1.623423,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,117.9914,29.29
3707,ZW,2021,2.573627e+09,2.560172e+07,6.233403,4.128767e+10,2613.605421,8.468017,2320.000000,98.546105,...,1.540911,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,162.9165,40.48
3708,ZW,2022,3.085043e+09,2.340965e+07,7.569254,4.075756e+10,2536.400502,6.139263,2580.000000,104.705171,...,1.812950,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,191.9866,19.87
3709,ZW,2023,3.301268e+09,3.327118e+07,9.202966,3.587178e+10,2195.224921,5.350869,2550.000000,NaN,...,1.894917,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,202.0258,7.01

In [3]:
df.head() #prints first 5 rows

,country_code,year,remittances_received_usd,remittances_paid_usd,remittances_pct_gdp,gdp_usd,gdp_per_capita_usd,gdp_growth_pct,gni_per_capita_usd,inflation_cpi_pct,...,mobile_money_accounts_pct,country_name,region,income_group,capital_city,latitude,longitude,source_engine,remittances_per_capita_usd,remittances_growth_yoy
0,1A,2010,3.778065e+10,5.423934e+10,2.332815,2.161398e+12,5944.952173,4.840642,5774.981239,NaN,...,9.604438,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,103.9162,NaN
1,1A,2011,3.894486e+10,6.766183e+10,1.900776,2.573068e+12,6915.827681,3.853204,6088.034560,NaN,...,9.382147,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,104.6750,3.08
2,1A,2012,4.593362e+10,7.449443e+10,2.048791,2.813568e+12,7384.106828,5.493754,6953.254327,NaN,...,9.157613,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,120.5511,17.95
3,1A,2013,4.722886e+10,8.559665e+10,2.026886,2.883690e+12,7376.028296,2.647321,7360.490201,NaN,...,8.472539,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,120.8040,2.82
4,1A,2014,5.312215e+10,8.700395e+10,2.226287,2.937036e+12,7338.350927,2.659752,7407.961860,NaN,...,7.240058,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,132.7287,12.48

In [4]:
df.tail() #prints last 5 rows

,country_code,year,remittances_received_usd,remittances_paid_usd,remittances_pct_gdp,gdp_usd,gdp_per_capita_usd,gdp_growth_pct,gni_per_capita_usd,inflation_cpi_pct,...,mobile_money_accounts_pct,country_name,region,income_group,capital_city,latitude,longitude,source_engine,remittances_per_capita_usd,remittances_growth_yoy
3705,ZW,2019,1.417012e+09,1.348057e+07,4.247931,3.335770e+10,2184.329239,-6.332450,2430.0,255.304991,...,1.740080,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,92.7888,-0.75
3706,ZW,2020,1.832039e+09,2.170709e+07,5.728644,3.198033e+10,2059.674454,-7.816951,1980.0,557.201817,...,1.623423,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,117.9914,29.29
3707,ZW,2021,2.573627e+09,2.560172e+07,6.233403,4.128767e+10,2613.605421,8.468017,2320.0,98.546105,...,1.540911,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,162.9165,40.48
3708,ZW,2022,3.085043e+09,2.340965e+07,7.569254,4.075756e+10,2536.400502,6.139263,2580.0,104.705171,...,1.812950,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,191.9866,19.87
3709,ZW,2023,3.301268e+09,3.327118e+07,9.202966,3.587178e+10,2195.224921,5.350869,2550.0,NaN,...,1.894917,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,202.0258,7.01

In [6]:
df.sample(5) #prints randomly 5 rows

,country_code,year,remittances_received_usd,remittances_paid_usd,remittances_pct_gdp,gdp_usd,gdp_per_capita_usd,gdp_growth_pct,gni_per_capita_usd,inflation_cpi_pct,...,mobile_money_accounts_pct,country_name,region,income_group,capital_city,latitude,longitude,source_engine,remittances_per_capita_usd,remittances_growth_yoy
1780,MA,2012,6.507905e+09,6.415293e+07,6.085715,1.069374e+11,3164.177246,3.062344,3230.000000,1.287122,...,9.830701,MA,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,195.1089,-10.31
780,DK,2020,1.332177e+09,3.402495e+09,0.374595,3.556310e+11,60985.488560,-1.780106,62710.000000,0.420712,...,12.594225,DK,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,228.4487,-8.10
2947,TJ,2017,2.237179e+09,2.155523e+08,29.684972,7.536403e+09,829.457148,7.100000,1000.000000,NaN,...,2.648761,TJ,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,246.2241,19.80
39,4E,2021,8.334138e+10,4.373943e+10,0.401228,2.123143e+13,9974.578297,7.719796,9496.815541,NaN,...,10.000000,4E,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,39.1540,8.10
2287,PG,2015,3.944548e+06,2.806513e+08,0.018158,2.172344e+10,2484.596340,6.578356,2520.000000,5.995958,...,1.715610,PG,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,0.4512,-62.34

In [7]:
df.sample(10) #prints randomly 5 rows

,country_code,year,remittances_received_usd,remittances_paid_usd,remittances_pct_gdp,gdp_usd,gdp_per_capita_usd,gdp_growth_pct,gni_per_capita_usd,inflation_cpi_pct,...,mobile_money_accounts_pct,country_name,region,income_group,capital_city,latitude,longitude,source_engine,remittances_per_capita_usd,remittances_growth_yoy
2013,MV,2021,4.882675e+06,4.964661e+08,0.092960,5.252457e+09,10176.143883,37.507870,9350.000000,0.543150,...,2.713337,MV,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,9.4597,5.00
2137,NI,2019,1.686400e+09,1.600000e+06,13.279761,1.269902e+10,1958.620515,-2.896870,1930.000000,5.376290,...,3.528595,NI,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,260.1001,12.07
2292,PG,2020,2.297151e+06,3.333814e+07,0.009632,2.384845e+10,2429.611346,-3.167432,2410.000000,4.871674,...,1.691160,PG,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,0.2340,-92.17
2969,TM,2011,NaN,0.000000e+00,NaN,2.923333e+10,5143.619293,14.700000,4300.000000,NaN,...,9.624492,TM,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,NaN,NaN
3516,XU,2012,8.748376e+09,5.821753e+10,0.048364,1.808872e+13,51812.892121,2.243173,52467.805742,NaN,...,44.503982,XU,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,25.0586,2.84
799,DO,2011,4.240700e+09,5.655000e+08,7.318080,5.794826e+10,5826.510141,3.191962,5460.000000,5.796768,...,11.058032,DO,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,426.3887,9.10
2686,SN,2022,2.910590e+09,2.687177e+08,10.476030,2.778333e+10,1574.028106,3.850432,1600.000000,9.696819,...,1.682875,SN,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,164.8957,-6.01
3027,TT,2013,1.451296e+08,2.159386e+08,0.508147,2.856054e+10,21304.977750,3.368193,20110.000000,5.199817,...,20.620138,TT,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,108.2607,4.57
3435,XM,2015,1.045835e+10,3.228450e+09,3.470194,3.617825e+11,740.889504,-2.062947,718.699716,NaN,...,1.400000,XM,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,21.4175,12.41
563,CG,2013,7.205715e+07,5.696704e+07,0.401238,1.795872e+10,3697.417059,-0.712434,3560.000000,4.631616,...,0.322806,CG,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,14.8354,5.43

In [8]:
df.info() #basic info of DataSet

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3710 entries, 0 to 3709
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country_code                 3696 non-null   object
 1   year                         3710 non-null   int64
 2   remittances_received_usd     3164 non-null   float64
 3   remittances_paid_usd         3500 non-null   float64
 4   remittances_pct_gdp          3149 non-null   float64
 5   gdp_usd                      3624 non-null   float64
 6   gdp_per_capita_usd           3624 non-null   float64
 7   gdp_growth_pct               3604 non-null   float64
 8   gni_per_capita_usd           3475 non-null   float64
 9   inflation_cpi_pct            2617 non-null   float64
 10  unemployment_pct             3286 non-null   float64
 11  current_account_pct_gdp      2582 non-null   float64
 12  population_total             3710 non-null   float64
 13  population_growth_pct        3709 non-null   float64
 14  urban_population_pct         3710 non-null   float64
 15  personal_remittances_recv    3164 non-null   float64
 16  personal_remittances_paid    3500 non-null   float64
 17  net_migration                3710 non-null   float64
 18  migrant_stock_total          789 non-null    float64
 19  poverty_headcount_pct        1312 non-null   float64
 20  life_expectancy_years        3710 non-null   float64
 21  remittance_cost_inward_pct   780 non-null    float64
 22  remittance_cost_outward_pct  353 non-null    float64
 23  forex_reserves_usd           2447 non-null   float64
 24  fdi_inflows_usd              3433 non-null   float64
 25  bank_branches_per_100k       3081 non-null   float64
 26  atms_per_100k                3080 non-null   float64
 27  mobile_money_accounts_pct    3492 non-null   float64
 28  country_name                 3696 non-null   object
 29  region                       3710 non-null   object
 30  income_group                 3710 non-null   object
 31  capital_city                 3710 non-null   object
 32  latitude                     3710 non-null   float64
 33  longitude                    3710 non-null   float64
 34  source_engine                3710 non-null   object
 35  remittances_per_capita_usd   3164 non-null   float64
 36  remittances_growth_yoy       2923 non-null   float64
dtypes: float64(30), int64(1), object(6)
memory usage: 1.0+ MB

In [9]:
df.describe() #gives stats summary

,year,remittances_received_usd,remittances_paid_usd,remittances_pct_gdp,gdp_usd,gdp_per_capita_usd,gdp_growth_pct,gni_per_capita_usd,inflation_cpi_pct,unemployment_pct,...,remittance_cost_outward_pct,forex_reserves_usd,fdi_inflows_usd,bank_branches_per_100k,atms_per_100k,mobile_money_accounts_pct,latitude,longitude,remittances_per_capita_usd,remittances_growth_yoy
count,3710.000000,3.164000e+03,3.500000e+03,3149.000000,3.624000e+03,3624.000000,3604.000000,3475.000000,2617.000000,3286.000000,...,353.000000,2.447000e+03,3.433000e+03,3081.000000,3080.000000,3492.000000,3710.0,3710.0,3164.000000,2923.000000
mean,2016.500000,2.755877e+10,1.254100e+10,4.412568,2.665748e+12,17151.593386,2.958571,14692.044262,6.407837,7.600077,...,5.347357,7.835171e+10,6.425258e+10,16.592993,46.113082,17.205450,0.0,0.0,340.460170,62.866921
std,4.031672,7.774928e+10,4.576537e+10,6.139164,9.200446e+12,25766.605724,5.820896,19918.588276,20.207711,5.423091,...,3.280721,2.962366e+11,2.274914e+11,18.172850,45.431319,17.737169,0.0,0.0,1573.437668,1575.588641
min,2010.000000,2.047511e+05,0.000000e+00,0.000163,3.210541e+07,216.727705,-54.402093,200.000000,-12.563149,0.100000,...,0.410000,8.184292e+06,-3.434028e+11,0.040090,0.090652,0.000000,0.0,0.0,0.008500,-98.860000
25%,2013.000000,2.314667e+08,4.787312e+07,0.602312,9.436586e+09,2166.653238,1.237475,2060.000000,1.401959,4.049000,...,3.052615,9.691243e+08,2.128097e+08,5.711477,11.016864,2.338115,0.0,0.0,39.708925,-1.870000
50%,2016.500000,1.505247e+09,3.046175e+08,2.219150,5.301205e+10,6538.552239,3.215696,6010.000000,3.240028,6.011105,...,4.375048,5.587739e+09,1.583000e+09,12.384668,37.516672,12.900487,0.0,0.0,116.242900,4.730000
75%,2020.000000,9.550002e+09,4.821439e+09,5.228418,5.712834e+11,21382.817361,5.313949,18069.499420,6.329040,9.334000,...,6.696000,4.049626e+10,2.010282e+10,21.980885,62.410827,25.194649,0.0,0.0,301.500050,12.230000
max,2023.000000,7.994185e+11,5.946499e+11,49.895312,1.067416e+14,256799.788613,86.826748,134500.000000,557.201817,36.472000,...,17.830660,3.900039e+12,2.793914e+12,273.091168,314.768862,140.085252,0.0,0.0,31458.753600,59051.700000

In [10]:
df

,country_code,year,remittances_received_usd,remittances_paid_usd,remittances_pct_gdp,gdp_usd,gdp_per_capita_usd,gdp_growth_pct,gni_per_capita_usd,inflation_cpi_pct,...,mobile_money_accounts_pct,country_name,region,income_group,capital_city,latitude,longitude,source_engine,remittances_per_capita_usd,remittances_growth_yoy
0,1A,2010,3.778065e+10,5.423934e+10,2.332815,2.161398e+12,5944.952173,4.840642,5774.981239,NaN,...,9.604438,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,103.9162,NaN
1,1A,2011,3.894486e+10,6.766183e+10,1.900776,2.573068e+12,6915.827681,3.853204,6088.034560,NaN,...,9.382147,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,104.6750,3.08
2,1A,2012,4.593362e+10,7.449443e+10,2.048791,2.813568e+12,7384.106828,5.493754,6953.254327,NaN,...,9.157613,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,120.5511,17.95
3,1A,2013,4.722886e+10,8.559665e+10,2.026886,2.883690e+12,7376.028296,2.647321,7360.490201,NaN,...,8.472539,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,120.8040,2.82
4,1A,2014,5.312215e+10,8.700395e+10,2.226287,2.937036e+12,7338.350927,2.659752,7407.961860,NaN,...,7.240058,1A,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,132.7287,12.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3705,ZW,2019,1.417012e+09,1.348057e+07,4.247931,3.335770e+10,2184.329239,-6.332450,2430.000000,255.304991,...,1.740080,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,92.7888,-0.75
3706,ZW,2020,1.832039e+09,2.170709e+07,5.728644,3.198033e+10,2059.674454,-7.816951,1980.000000,557.201817,...,1.623423,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,117.9914,29.29
3707,ZW,2021,2.573627e+09,2.560172e+07,6.233403,4.128767e+10,2613.605421,8.468017,2320.000000,98.546105,...,1.540911,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,162.9165,40.48
3708,ZW,2022,3.085043e+09,2.340965e+07,7.569254,4.075756e+10,2536.400502,6.139263,2580.000000,104.705171,...,1.812950,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,191.9866,19.87
3709,ZW,2023,3.301268e+09,3.327118e+07,9.202966,3.587178e+10,2195.224921,5.350869,2550.000000,NaN,...,1.894917,ZW,Unknown,Unknown,Unknown,0.0,0.0,world_bank_v2,202.0258,7.01

In [16]:
#Acessing a column index
df_indexed = df.set_index('country_code')
print(" *** DataFrame with country_code as index***:\n", df_indexed)

 *** DataFrame with country_code as index***:
               year  remittances_received_usd  remittances_paid_usd  \
country_code
1A            2010              3.778065e+10          5.423934e+10
1A            2011              3.894486e+10          6.766183e+10
1A            2012              4.593362e+10          7.449443e+10
1A            2013              4.722886e+10          8.559665e+10
1A            2014              5.312215e+10          8.700395e+10
...            ...                       ...                   ...
ZW            2019              1.417012e+09          1.348057e+07
ZW            2020              1.832039e+09          2.170709e+07
ZW            2021              2.573627e+09          2.560172e+07
ZW            2022              3.085043e+09          2.340965e+07
ZW            2023              3.301268e+09          3.327118e+07

              remittances_pct_gdp       gdp_usd  gdp_per_capita_usd  \
country_code
1A                       2.332815  2.161398e+12         5944.952173
1A                       1.900776  2.573068e+12         6915.827681
1A                       2.048791  2.813568e+12         7384.106828
1A                       2.026886  2.883690e+12         7376.028296
1A                       2.226287  2.937036e+12         7338.350927
...                           ...           ...                 ...
ZW                       4.247931  3.335770e+10         2184.329239
ZW                       5.728644  3.198033e+10         2059.674454
ZW                       6.233403  4.128767e+10         2613.605421
ZW                       7.569254  4.075756e+10         2536.400502
ZW                       9.202966  3.587178e+10         2195.224921

              gdp_growth_pct  gni_per_capita_usd  inflation_cpi_pct  \
country_code
1A                  4.840642         5774.981239                NaN
1A                  3.853204         6088.034560                NaN
1A                  5.493754         6953.254327                NaN
1A                  2.647321         7360.490201                NaN
1A                  2.659752         7407.961860                NaN
...                      ...                 ...                ...
ZW                 -6.332450         2430.000000         255.304991
ZW                 -7.816951         1980.000000         557.201817
ZW                  8.468017         2320.000000          98.546105
ZW                  6.139263         2580.000000         104.705171
ZW                  5.350869         2550.000000                NaN

              unemployment_pct  ...  mobile_money_accounts_pct  country_name  \
country_code                    ...
1A                    9.571788  ...                   9.604438            1A
1A                   10.687395  ...                   9.382147            1A
1A                   11.065097  ...                   9.157613            1A
1A                   11.035002  ...                   8.472539            1A
1A                   11.031926  ...                   7.240058            1A
...                        ...  ...                        ...           ...
ZW                    7.373000  ...                   1.740080            ZW
ZW                    8.617000  ...                   1.623423            ZW
ZW                    9.540000  ...                   1.540911            ZW
ZW                   10.087000  ...                   1.812950            ZW
ZW                    9.348000  ...                   1.894917            ZW

               region  income_group  capital_city  latitude  longitude  \
country_code
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
...               ...           ...           ...       ...        ...
ZW            Unknown       Unknown       Unknown       0.0        0.0
ZW            Unknown       Unknown       Unknown       0.0        0.0
ZW            Unknown       Unknown       Unknown       0.0        0.0
ZW            Unknown       Unknown       Unknown       0.0        0.0
ZW            Unknown       Unknown       Unknown       0.0        0.0

              source_engine  remittances_per_capita_usd  \
country_code
1A            world_bank_v2                    103.9162
1A            world_bank_v2                    104.6750
1A            world_bank_v2                    120.5511
1A            world_bank_v2                    120.8040
1A            world_bank_v2                    132.7287
...                     ...                         ...
ZW            world_bank_v2                     92.7888
ZW            world_bank_v2                    117.9914
ZW            world_bank_v2                    162.9165
ZW            world_bank_v2                    191.9866
ZW            world_bank_v2                    202.0258

              remittances_growth_yoy
country_code
1A                               NaN
1A                              3.08
1A                             17.95
1A                              2.82
1A                             12.48
...                              ...
ZW                             -0.75
ZW                             29.29
ZW                             40.48
ZW                             19.87
ZW                              7.01

[3710 rows x 36 columns]

In [17]:
###Access a row using index###
print("\n*** Row for index 1A ***:\n", df_indexed.loc['1A'])

*** Row for index 1A ***:
               year  remittances_received_usd  remittances_paid_usd  \
country_code
1A            2010              3.778065e+10          5.423934e+10
1A            2011              3.894486e+10          6.766183e+10
1A            2012              4.593362e+10          7.449443e+10
1A            2013              4.722886e+10          8.559665e+10
1A            2014              5.312215e+10          8.700395e+10
1A            2015              4.932802e+10          8.661684e+10
1A            2016              4.865741e+10          8.470168e+10
1A            2017              5.168558e+10          8.195513e+10
1A            2018              5.273131e+10          8.093177e+10
1A            2019              5.507635e+10          8.159893e+10
1A            2020              5.758399e+10          7.926412e+10
1A            2021              6.667699e+10          8.598752e+10
1A            2022              6.424236e+10          8.754511e+10
1A            2023              5.570397e+10          1.379555e+11

              remittances_pct_gdp       gdp_usd  gdp_per_capita_usd  \
country_code
1A                       2.332815  2.161398e+12         5944.952173
1A                       1.900776  2.573068e+12         6915.827681
1A                       2.048791  2.813568e+12         7384.106828
1A                       2.026886  2.883690e+12         7376.028296
1A                       2.226287  2.937036e+12         7338.350927
1A                       2.362081  2.580329e+12         6290.558795
1A                       2.378823  2.536565e+12         6042.196754
1A                       2.517854  2.611324e+12         6096.723950
1A                       2.279742  2.920830e+12         6699.180582
1A                       2.325338  2.965286e+12         6674.342244
1A                       2.711933  2.604105e+12         5739.412836
1A                       2.621557  3.085141e+12         6697.414985
1A                       2.079748  3.747417e+12         7950.355820
1A                       1.618354  3.622496e+12         7513.899079

              gdp_growth_pct  gni_per_capita_usd  inflation_cpi_pct  \
country_code
1A                  4.840642         5774.981239                NaN
1A                  3.853204         6088.034560                NaN
1A                  5.493754         6953.254327                NaN
1A                  2.647321         7360.490201                NaN
1A                  2.659752         7407.961860                NaN
1A                  3.350804         6936.644790                NaN
1A                  3.572868         6479.267312                NaN
1A                  1.329010         6048.461307                NaN
1A                  2.672553         6328.949740                NaN
1A                  1.747781         6590.574169                NaN
1A                 -5.301028         6062.329318                NaN
1A                  4.431609         6472.741567                NaN
1A                  7.007759         7279.320431                NaN
1A                  1.634950         7649.383468                NaN

              unemployment_pct  ...  mobile_money_accounts_pct  country_name  \
country_code                    ...
1A                    9.571788  ...                   9.604438            1A
1A                   10.687395  ...                   9.382147            1A
1A                   11.065097  ...                   9.157613            1A
1A                   11.035002  ...                   8.472539            1A
1A                   11.031926  ...                   7.240058            1A
1A                   11.152446  ...                   7.403380            1A
1A                   10.861716  ...                   7.644471            1A
1A                   11.115202  ...                   8.153360            1A
1A                   10.654641  ...                   8.237892            1A
1A                   10.213718  ...                   8.398400            1A
1A                   11.295150  ...                   8.674176            1A
1A                   10.862749  ...                   8.990483            1A
1A                    9.744131  ...                   9.481065            1A
1A                    9.313389  ...                        NaN            1A

               region  income_group  capital_city  latitude  longitude  \
country_code
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0
1A            Unknown       Unknown       Unknown       0.0        0.0

              source_engine  remittances_per_capita_usd  \
country_code
1A            world_bank_v2                    103.9162
1A            world_bank_v2                    104.6750
1A            world_bank_v2                    120.5511
1A            world_bank_v2                    120.8040
1A            world_bank_v2                    132.7287
1A            world_bank_v2                    120.2563
1A            world_bank_v2                    115.9039
1A            world_bank_v2                    120.6716
1A            world_bank_v2                    120.9439
1A            world_bank_v2                    123.9673
1A            world_bank_v2                    126.9144
1A            world_bank_v2                    144.7465
1A            world_bank_v2                    136.2938
1A            world_bank_v2                    115.5430

              remittances_growth_yoy
country_code
1A                               NaN
1A                              3.08
1A                             17.95
1A                              2.82
1A                             12.48
1A                             -7.14
1A                             -1.36
1A                              6.22
1A                              2.02
1A                              4.45
1A                              4.55
1A                             15.79
1A                             -3.65
1A                            -13.29

[14 rows x 36 columns]